#!/bin/bash
# Runs a C file through the preprocessor and saves the result into another file

# The C file name is saved in the variable $CFILE
# The output is saved in the file 'c'
gcc -E "$CFILE" -o c
